#
# https://medium.com/flawless-app-stories/swiftlint-in-use-279f44b3182e
# https://regex101.com/
#

excluded:
    - Carthage

custom_rules:

    no_letUnderscore:
        included: ".*\\.swift"
        name: "No let _ = ..."
        regex: 'let[ ][_][ ][=]'
        message: "Don't use let _ = xxx , use xxx != nil"
        severity: error

    naming_Singletons:
        included: ".*\\.swift"
        name: "Singleton naming"
        regex: "static (var|let)[ ](instance|sharedInstance)[ ]*[:]"
        message: "Use shared"
        severity: error

    no_hardCodedTimeZones:
        included: ".*\\.swift"
        name: "Fordiden hardcoded TimeZones"
        regex: "\"UTC\"|\"GMT\""
        message: "Use AppConstants.TimeZones..."
        severity: error

    no_TODO:
        included: ".*\\.swift"
        name: "Fordiden TODO/FIX"
        regex: "TODO|TO DO|FIX"
        message: "Use #warning"
        severity: error

    no_hardCodedDateFormats:
        included: ".*\\.swift"
        name: "Hardcoded DateFormats"
        regex: '= "yyyy|DateFormatter(withFormat'
        message: "Use a DateFormats on AppContants.Date or DateFormatterTypes"
        severity: error

    no_print:
        included: ".*\\.swift"
        name: "Fordiden print"
        regex: "print[(]"
        message: "Use AppLogger..."
        severity: warning

    no_hardCodedImages:
        included: ".*\\.swift"
        name: "Fordiden hardCoded images"
        regex: "(image|[(]named]|imageLiteralResourceName|highlightedResource|resourceName){1}[ ]*[:][ ]*[\"]"
        message: "Don't use hardCoded images"
        severity: error

#numbers_smell:
#    regex: '(return |case |\w\(|: |\?\? |\, |== |<=? |>=? |\+= |\-= |\/= |\*= |%= |\w\.\w+ = )\(*-?\d{2,}'
#    message: "Numbers smell; define a constant instead."
#    severity: warning

#    multiline_commented_code:
#        regex: '^\s*[a-z]'
#        match_kinds: comment
#        message: "Comment starting with lowercase letter - did you forget to delete old code?"
#        severity: warning

#    commented_code:
#        regex: '(?<!:|\/)\/\/\h*[a-z.](?!wiftlint)'
#        message: "Comment starting with lowercase letter - did you forget to delete old code?"
#        severity: warning

file_length:
    - 750  # warning
    - 1000 # error

type_body_length:
    - 500  # warning
    - 1000 # error

large_tuple:
    - 4  # warning
    - 5  # error

empty_enum_arguments:
    warning

force_try:
    warning

force_cast:
    warning

line_length:
    warning: 175
    error: 300

nesting:
    type_level:
        warning: 3

type_name:
    max_length: 60
    allowed_symbols: "_"
    excluded:
        - iPhone
        - R
        - RP
        - AC
        - UC
        - MP
        - V
        - VM
        - VC
        - AS
        - Rx
        - W
        - P
        - I
        - E
        - MD
        - M
        - Id

identifier_name:
    max_length: 60
    excluded:
        - iPhone
        - id

function_parameter_count: 10

disabled_rules:
    - todo
    - valid_ibinspectable
    - identifier_name
    - trailing_whitespace

#
# THE RULES BELOW ARE NOT TO BE DELETED
#  All warnings of this type were fixed @ 31-03-2020, please don't do more...
#

duplicate_imports:
    severity: error

operator_whitespace:
    severity: error

redundant_string_enum_value:
    severity: error

trailing_newline:
    severity: error

statement_position:
    severity: error

unused_closure_parameter:
    severity: error

vertical_whitespace:
    severity: error

implicit_getter:
    severity: warning

colon:
    severity: error

shorthand_operator:
    severity: error

trailing_comma:
    severity: error

comma:
    severity: error

redundant_void_return:
    severity: error

return_arrow_whitespace:
    severity: error

opening_brace:
    severity: error

no_space_in_method_call:
    severity: error
